apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ include "nginx-app.name" . }}
